---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bookstackapp
  namespace: hihello
spec:
  releaseName: stable-bookstackapp
  interval: 1m
  chart:
    spec:
      chart: ./bookstack
      sourceRef: 
        kind: GitRepository
        name: new-repository
        # Optional, defaults to the namespace of the HelmRelease
        namespace: hihello
    # git: https://github.com/Improwised/charts   #https://github.com/dharmendrakariya/Learning.git
    # path: bookstack
    # ref: bookstack
  values:
    image:
      # repository: linuxserver/bookstack
      # tag: version-v0.31.1
      repository: solidnerd/bookstack
      tag: 0.29.3
    env: 
      APP_DEBUG: true
    externalDatabase:
      ## Database host
      #host: private-mysql-1-do-user-175693-0.b.db.ondigitalocean.com:25060   # DO
      host: mysql:3306
      
      ## Database user
      # user: bookstack   # DO
      user: bookstackuser
      ## Database password
      # password: foc5ugk0q3h5auqq  # DO
      password: bookStack123
      
      ## Database name
      # database: bookstack  # DO
      database: bookstackapp

    mariadb:
      ## Whether to deploy a mariadb server to satisfy the applications database requirements. To use an external database set this to false and configure the externalDatabase parameters
      enabled: true

    ingress:
      enabled: false
      # annotations: 
      #   kubernetes.io/ingress.class: nginx
      #   kubernetes.io/tls-acme: "true"
      path: /
      #backend:
        #serviceName: {{ $fullName }}
        #servicePort: 80
      hosts:
        - wiki.improwised.testyyy

    resources: 
      # We usually recommend not to specify default resources and to leave this as a conscious
      # choice for the user. This also increases chances charts run on environments with little
      # resources, such as Minikube. If you do want to specify resources, uncomment the following
      # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
      limits:
       cpu: 350m
       memory: 256Mi
      requests:
       cpu: 150m
       memory: 128Mi
    ldap:
      enabled: false
      server:
      base_dn:
      dn:
      pass:
      userFilter:
      version:
    livenessProbe:
      enabled: false
      failureThreshold: 3
      initialDelaySeconds: 30 # very conservative value, to give enough time for database migrations
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    readinessProbe:
      enabled: false
      failureThreshold: 3
      initialDelaySeconds: 30 # very conservative value, to give enough time for database migrations
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
